[build]
  command = "npm install && npm run build"
  base = "frontend/job-app-website"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
