// netlify.toml
[build]
  command = "npm run build"
  publish = ".next"
  base = "frontend/job-app-website"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200