[build]
  command = "cd frontend/job-app-website && npm install && npm run build"
  publish = "frontend/job-app-website/.next"
  base = "frontend/job-app-website"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200